export const POSTJOB = {
  SET_JOBINFO: "SET_JOBINFO",
  GET_TOPFREELANCERS: "GET_TOPFREELANCERS",
  GET_TOPFREELANCERS_SUCCESS: "GET_TOPFREELANCERS_SUCCESS",
  GET_TOPFREELANCERS_FAILED: "GET_TOPFREELANCERS_FAILED",
  GET_CONFIRMCODE: "GET_CONFIRMCODE",
  GET_CONFIRMCODE_SUCCESS: "GET_CONFIRMCODE_SUCCESS",
  GET_CONFIRMCODE_FAILED: "GET_CONFIRMCODE_FAILED"
}